from . import federation_club_role_type
from . import federation_club_representative
from . import federation_club
from . import federation_tournament
from . import res_partner
from . import res_users
from . import federation_tournament_registration
from . import federation_season_registration
from . import federation_team_roster