{
    "name": "Sports Federation Governance",
    "version": "19.0.1.0.0",
    "category": "Sports",
    "summary": "Controlled override requests, decisions, and audit notes for federation governance",
    "author": "Sports Federation",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "sports_federation_base",
        "mail",
    ],
    "data": [
        "security/governance_security.xml",
        "security/ir.model.access.csv",
        "views/override_request_views.xml",
        "views/override_decision_views.xml",
        "views/audit_note_views.xml",
        "views/menu_views.xml",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
    "sequence": 80,
}