{
    "name": "Sports Federation Reporting",
    "version": "19.0.1.1.0",
    "category": "Sports",
    "summary": "Reporting models for federation data",
    "author": "Sports Federation",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "web",
        "sports_federation_base",
        "sports_federation_people",
        "sports_federation_tournament",
        "sports_federation_officiating",
        "sports_federation_standings",
        "sports_federation_discipline",
        "sports_federation_compliance",
        "sports_federation_finance_bridge",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/report_participation_views.xml",
        "views/report_officiating_views.xml",
        "views/report_compliance_views.xml",
        "views/report_finance_views.xml",
        "views/menu_views.xml",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
    "sequence": 75,
}