{
    "name": "Sports Federation Club Roles",
    "version": "19.0.1.0.0",
    "category": "Sports",
    "summary": "Club contacts, representative roles, and portal ownership model for federation use",
    "author": "Sports Federation",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "sports_federation_base",
    ],
    "data": [
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "security/ir_rule.xml",
        "data/federation_club_role_type.xml",
        "views/federation_club_role_type_views.xml",
        "views/federation_club_representative_views.xml",
        "views/federation_club_views.xml",
        "views/res_partner_views.xml",
        "views/res_users_views.xml",
        "views/menu_items.xml",
    ],
    "demo": [],
    "installable": True,
    "application": False,
    "auto_install": False,
    "sequence": 15,
}