{
    "name": "Sports Federation Portal",
    "version": "19.0.1.0.0",
    "category": "Sports",
    "summary": "Public website and portal registration flows for clubs and tournaments",
    "author": "Sports Federation",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "website",
        "portal",
        "sports_federation_base",
        "sports_federation_tournament",
        "sports_federation_club_roles",
    ],
    "data": [
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "security/ir_rule.xml",
        "data/ir_sequence.xml",
        "views/website_tournament_templates.xml",
        "views/portal_templates.xml",
        "views/federation_tournament_registration_views.xml",
        "views/federation_club_representative_views.xml",
        "views/website_menus.xml",
    ],
    "demo": [],
    "installable": True,
    "application": False,
    "auto_install": False,
}