{
    "name": "Sports Federation Club Roles & Portal",
    "version": "19.0.1.0.0",
    "category": "Sports",
    "summary": "Club contacts, representative roles, portal website and registration flows",
    "author": "Sports Federation",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "website",
        "portal",
        "sports_federation_base",
        "sports_federation_tournament",
    ],
    "data": [
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "security/ir_rule.xml",
        "data/federation_club_role_type.xml",
        "data/ir_sequence.xml",
        "views/federation_club_role_type_views.xml",
        "views/federation_club_representative_views.xml",
        "views/federation_club_views.xml",
        "views/res_partner_views.xml",
        "views/res_users_views.xml",
        "views/federation_tournament_registration_views.xml",
        "views/federation_club_representative_portal_views.xml",
        "views/website_tournament_templates.xml",
        "views/portal_templates.xml",
        "views/menu_items.xml",
        "views/website_menus.xml",
    ],
    "demo": [],
    "installable": True,
    "application": False,
    "auto_install": False,
    "sequence": 15,
}